# Mandelbrot set

In [2]:
import numpy as np

In [11]:
a = np.array([1+2j, 3+4j, 5+6j])
a**2+a

array([-2. +6.j, -4.+28.j, -6.+66.j])

In [38]:
x_start=-10
x_end = 10
y_start=-10
y_end = 10
step = 0.1
x,y=np.mgrid[x_start:x_end:step, y_start:y_end:step]
complex_space = np.zeros(shape=(len(x),len(y)), dtype=complex)

In [39]:
complex_space

array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]])

In [42]:
complex_space.real=x
complex_space.imag=y
complex_space

array([[-10. -10.j , -10.  -9.9j, -10.  -9.8j, ..., -10.  +9.7j,
        -10.  +9.8j, -10.  +9.9j],
       [ -9.9-10.j ,  -9.9 -9.9j,  -9.9 -9.8j, ...,  -9.9 +9.7j,
         -9.9 +9.8j,  -9.9 +9.9j],
       [ -9.8-10.j ,  -9.8 -9.9j,  -9.8 -9.8j, ...,  -9.8 +9.7j,
         -9.8 +9.8j,  -9.8 +9.9j],
       ...,
       [  9.7-10.j ,   9.7 -9.9j,   9.7 -9.8j, ...,   9.7 +9.7j,
          9.7 +9.8j,   9.7 +9.9j],
       [  9.8-10.j ,   9.8 -9.9j,   9.8 -9.8j, ...,   9.8 +9.7j,
          9.8 +9.8j,   9.8 +9.9j],
       [  9.9-10.j ,   9.9 -9.9j,   9.9 -9.8j, ...,   9.9 +9.7j,
          9.9 +9.8j,   9.9 +9.9j]])